#!/bin/bash

if `defaults read com.apple.ncprefs.plist dnd_prefs | grep d6010203 > /dev/null`; then
echo 'on'
fi

if `defaults read com.apple.ncprefs.plist dnd_prefs | grep d5010203 > /dev/null`; then
echo 'off'
fi

